spring.application.name=Simulator
spring.datasource.url=jdbc:postgresql://localhost:5432/fintradex
spring.datasource.username=postgres
spring.datasource.password=Postgres@12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ThisIsMyVerySecretKeyForFinTradeXProject
jwt.expiration=86400000

twelvedata.api.key=e70192aae0f04c71a678b52064d956d1
twelvedata.base.url=https://api.twelvedata.com